=== DavidAnson/simple-website-with-blog/post-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "simple-website-with-blog post schema",
  "type": "object",
  "properties": {
    "contentDate": {
      "description": "UTC date/time of content",
      "type": "string",
      "pattern": "^\\d\\d\\d\\d-\\d\\d-\\d\\dT\\d\\d:\\d\\dZ$",
      "default": "1970-01-01T00:00Z"
    },
    "contentJson": {
      "description": "JSON object for content",
      "default": null
    },
    "publishDate": {
      "description": "UTC date/time to publish",
      "type": "string",
      "pattern": "^\\d\\d\\d\\d-\\d\\d-\\d\\dT\\d\\d:\\d\\dZ$",
      "default": "1970-01-01T00:00Z"
    },
    "related": {
      "description": "IDs of related posts",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "tags": {
      "description": "Tags for post",
      "type": "array",
      "items": {
        "type": "string"
      },
      "default": []
    },
    "title": {
      "description": "Title of post",
      "type": "string"
    }
  },
  "required": [
    "title"
  ],
  "additionalProperties": false
}

=== DavidAnson/simple-website-with-blog/sites/sample-photo/posts/portrait.json
{
  "title": "Portrait Photo",
  "publishDate": "2018-01-01T12:00Z",
  "contentDate": "2016-07-08T12:00Z",
  "contentJson": [
    {
      "image": "portrait.jpg",
      "image2x": "portrait-2x.jpg",
      "caption": "A photograph in portrait orientation"
    }
  ],
  "related": [
    "landscape",
    "twophotos"
  ]
}

=== DavidAnson/simple-website-with-blog/sites/sample-photo/posts/landscape.json
{
  "title": "Landscape Photo",
  "publishDate": "2018-02-02T12:00Z",
  "contentDate": "2017-08-09T12:00Z",
  "contentJson": [
    {
      "image": "landscape.jpg",
      "image2x": "landscape-2x.jpg",
      "caption": "A photograph in landscape orientation"
    }
  ],
  "related": [
    "portrait",
    "twophotos"
  ]
}
